RAZORPAY_KEY_ID = "rzp_test_rzp_test_RdcpseIKg6MAwm"
RAZORPAY_KEY_SECRET = "3ApXZA9MmlNImaeHvXY3aB4F"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = "587"
SENDER_EMAIL = "pushp.singh13@gmail.com"
SENDER_PASSWORD = "khzx jwld axxv dkey"
ADMIN_PASSWORD = "your_admin_password"
OWNER_EMAIL = "pushp.singh13@gmail.com"
SEND_TIME = "09:50"







